@TOKEN_USER=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImdVZHY5WTZ1SjBiQTk3NThSYjVuIiwiZW1haWwiOiJsZW9AZ21haWwuY29tIiwiaWF0IjoxNzU3NzIxNDQ3LCJleHAiOjE3NTc3MjUwNDd9.qND1-r_Dr0EH0ZlXi-6i7ZQn1SNWhMRKIBckq6CnLfg

POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer {{TOKEN_USER}}

{
    "title": "Tarea4",
    "description": "Configurar CI CD con Github Actions",
    "completed": false
}

###
GET http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer {{TOKEN_USER}}

###
PUT http://localhost:3000/tasks/E4xBaDCxRdEeTzb1Sy6X
Content-Type: application/json
Authorization: Bearer {{TOKEN_USER}}

{
    "title": "Tarea1 actualizada",
    "description": "Configurar CI CD con Github Actions",
    "completed": true
}

###
DELETE http://localhost:3000/tasks/E4xBaDCxRdEeTzb1Sy6X
Content-Type: application/json
Authorization: Bearer {{TOKEN_USER}}

