@TOKEN_USER=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImdVZHY5WTZ1SjBiQTk3NThSYjVuIiwiZW1haWwiOiJsZW9AZ21haWwuY29tIiwiaWF0IjoxNzU3Njg4NzMzLCJleHAiOjE3NTc2OTIzMzN9.fTRCZAQiFEoaJC4lVHmbTYrHtLDvzFSLvkNw4vJ4Dzg

POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer {{TOKEN_USER}}

{
    "title": "Tarea1",
    "description": "Configurar CI CD",
    "userId": "gUdv9Y6uJ0bA9758Rb5n"
}
