name: Firebase Functions CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./functions
        run: npm install

      - name: Build
        working-directory: ./functions
        run: npm run build

      - name: Setup Firebase
        uses: w9jds/firebase-action@v3
        with:
          args: "deploy --only functions"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Run tests
        working-directory: ./functions
        run: npm run test