name: CI/CD Firebase Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Lint
        run: |
          cd functions
          npm run lint || echo "Lint warnings/errors ignored"

      - name: Run tests
        run: |
          cd functions
          npm run test

      - name: Build TypeScript
        run: |
          cd functions
          npm run build

      - name: Deploy to Firebase
        uses: firebase-actions/deploy-firebase-functions@v20.0.1
        with:
          firebase-project-id: ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
